### ISSUE TITLE
add in real time 

### ISSUE THREAD

**Issue by SJayYang** [mountwebs/timeglass#4]
Whenever you click on the icon, the time stops at the exact time whenever you clicked on the icon, rather than continuously counting down, which gave me the impression that the timer had stopped. Is there a way you can make it continuously count down whenever the menu is open?

**Comment by mountwebs** [comment]
I'm sorry about the very late reply. 

I agree. I would like it to show the time in real time, but I could not figure out how to do it. This might be limited by the rumps library. Feel free to make a pull request if you (or someone else) figures out how to make it work.
